import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'as' | 'bn' | 'tribal';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    appName: "Smart Health Monitoring",
    tagline: "Community Health & Water Quality",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी",
    assamese: "অসমীয়া",
    bengali: "বাংলা",
    tribal: "Tribal Dialects",
    continue: "Continue",
    admin: "Admin",
    ashaWorker: "ASHA Worker",
    selectRole: "Select Your Role",
    login: "Login",
    adminName: "Admin Name",
    villageName: "Village Name",
    workerId: "Worker ID",
    password: "Password",
    dashboard: "Dashboard",
    dataEntry: "Data Entry",
    reports: "Reports",
    alerts: "Alerts",
    settings: "Settings",
    patientInfo: "Patient Information",
    patientName: "Patient Name",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    symptoms: "Symptoms",
    waterQuality: "Water Quality",
    turbidity: "Turbidity",
    pH: "pH Level",
    temperature: "Temperature",
    safe: "Safe",
    warning: "Warning",
    unsafe: "Unsafe",
    saveData: "Save Data",
    addAshaWorker: "Add ASHA Worker",
    workerName: "Worker Name",
    generatePassword: "Generate Password",
    sendSMS: "Send SMS",
    viewCharts: "View Charts",
    healthTrends: "Health Trends",
    waterSourceCondition: "Water Source Condition",
    clean: "Clean",
    muddy: "Muddy",
    stagnant: "Stagnant",
    location: "Location",
    fever: "Fever",
    cough: "Cough",
    diarrhea: "Diarrhea",
    vomiting: "Vomiting",
    skinIssues: "Skin Issues",
    stomachPain: "Stomach Pain",
    headache: "Headache",
    bodyPain: "Body Pain"
  },
  hi: {
    appName: "स्मार्ट स्वास्थ्य निगरानी",
    tagline: "समुदायिक स्वास्थ्य और जल गुणवत्ता",
    selectLanguage: "भाषा चुनें",
    english: "English",
    hindi: "हिंदी",
    assamese: "অসমীয়া",
    bengali: "বাংলা",
    tribal: "जनजातीय भाषाएं",
    continue: "जारी रखें",
    admin: "प्रशासक",
    ashaWorker: "आशा कार्यकर्ता",
    selectRole: "अपनी भूमिका चुनें",
    login: "लॉगिन",
    adminName: "प्रशासक का नाम",
    villageName: "गांव का नाम",
    workerId: "कार्यकर्ता आईडी",
    password: "पासवर्ड",
    dashboard: "डैशबोर्ड",
    dataEntry: "डेटा एंट्री",
    reports: "रिपोर्ट",
    alerts: "अलर्ट",
    settings: "सेटिंग्स",
    patientInfo: "रोगी की जानकारी",
    patientName: "रोगी का नाम",
    age: "उम्र",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    symptoms: "लक्षण",
    waterQuality: "जल गुणवत्ता",
    turbidity: "मैलापन",
    pH: "पीएच स्तर",
    temperature: "तापमान",
    safe: "सुरक्षित",
    warning: "चेतावनी",
    unsafe: "असुरक्षित",
    saveData: "डेटा सेव करें",
    addAshaWorker: "आशा कार्यकर्ता जोड़ें",
    workerName: "कार्यकर्ता का नाम",
    generatePassword: "पासवर्ड बनाएं",
    sendSMS: "एसएमएस भेजें",
    viewCharts: "चार्ट देखें",
    healthTrends: "स्वास्थ्य रुझान",
    waterSourceCondition: "जल स्रोत की स्थिति",
    clean: "साफ",
    muddy: "गंदा",
    stagnant: "स्थिर",
    location: "स्थान",
    fever: "बुखार",
    cough: "खांसी",
    diarrhea: "दस्त",
    vomiting: "उल्टी",
    skinIssues: "त्वचा की समस्या",
    stomachPain: "पेट दर्द",
    headache: "सिर दर्द",
    bodyPain: "शरीर दर्द"
  },
  as: {
    appName: "স্মাৰ্ট স্বাস্থ্য নিৰীক্ষণ",
    tagline: "সম্প্ৰদায়িক স্বাস্থ্য আৰু পানীৰ গুণাগুণ",
    selectLanguage: "ভাষা নিৰ্বাচন কৰক",
    english: "English",
    hindi: "हिंदी",
    assamese: "অসমীয়া",
    bengali: "বাংলা",
    tribal: "জনজাতীয় ভাষা",
    continue: "অব্যাহত ৰাখক",
    admin: "প্ৰশাসক",
    ashaWorker: "আশা কৰ্মী",
    selectRole: "আপোনাৰ ভূমিকা নিৰ্বাচন কৰক",
    login: "লগইন",
    adminName: "প্ৰশাসকৰ নাম",
    villageName: "গাঁওৰ নাম",
    workerId: "কৰ্মী আইডি",
    password: "পাছৱৰ্ড",
    dashboard: "ডেছবৰ্ড",
    dataEntry: "তথ্য প্ৰবিষ্ট",
    reports: "প্ৰতিবেদন",
    alerts: "সতৰ্কবাণী",
    settings: "ছেটিংছ",
    patientInfo: "ৰোগীৰ তথ্য",
    patientName: "ৰোগীৰ নাম",
    age: "বয়স",
    gender: "লিংগ",
    male: "পুৰুষ",
    female: "মহিলা",
    other: "অন্য",
    symptoms: "লক্ষণ",
    waterQuality: "পানীৰ গুণাগুণ",
    turbidity: "ঘোলা",
    pH: "পিএইচ স্তৰ",
    temperature: "তাপমাত্ৰা",
    safe: "নিৰাপদ",
    warning: "সতৰ্কবাণী",
    unsafe: "বিপদজনক",
    saveData: "তথ্য সংৰক্ষণ কৰক",
    addAshaWorker: "আশা কৰ্মী যোগ কৰক",
    workerName: "কৰ্মীৰ নাম",
    generatePassword: "পাছৱৰ্ড তৈয়াৰ কৰক",
    sendSMS: "এছএমএছ পঠাওক",
    viewCharts: "চাৰ্ট চাওক",
    healthTrends: "স্বাস্থ্যৰ ধাৰা",
    waterSourceCondition: "পানীৰ উৎসৰ অবস্থা",
    clean: "পৰিষ্কাৰ",
    muddy: "কাদা",
    stagnant: "স্থিৰ",
    location: "স্থান",
    fever: "জ্বৰ",
    cough: "কাঁহ",
    diarrhea: "ডায়েৰিয়া",
    vomiting: "বমি",
    skinIssues: "ছালৰ সমস্যা",
    stomachPain: "পেটৰ বিষ",
    headache: "মূৰৰ বিষ",
    bodyPain: "শৰীৰৰ বিষ"
  },
  bn: {
    appName: "স্মার্ট স্বাস্থ্য নিরীক্ষণ",
    tagline: "কমিউনিটি স্বাস্থ্য ও পানির গুণমান",
    selectLanguage: "ভাষা নির্বাচন করুন",
    english: "English",
    hindi: "हिंदी",
    assamese: "অসমীয়া",
    bengali: "বাংলা",
    tribal: "উপজাতীয় ভাষা",
    continue: "অব্যাহত রাখুন",
    admin: "প্রশাসক",
    ashaWorker: "আশা কর্মী",
    selectRole: "আপনার ভূমিকা নির্বাচন করুন",
    login: "লগইন",
    adminName: "প্রশাসকের নাম",
    villageName: "গ্রামের নাম",
    workerId: "কর্মী আইডি",
    password: "পাসওয়ার্ড",
    dashboard: "ড্যাশবোর্ড",
    dataEntry: "ডেটা এন্ট্রি",
    reports: "রিপোর্ট",
    alerts: "সতর্কতা",
    settings: "সেটিংস",
    patientInfo: "রোগীর তথ্য",
    patientName: "রোগীর নাম",
    age: "বয়স",
    gender: "লিঙ্গ",
    male: "পুরুষ",
    female: "মহিলা",
    other: "অন্যান্য",
    symptoms: "লক্ষণ",
    waterQuality: "পানির গুণমান",
    turbidity: "ঘোলাটে",
    pH: "পিএইচ স্তর",
    temperature: "তাপমাত্রা",
    safe: "নিরাপদ",
    warning: "সতর্কতা",
    unsafe: "বিপজ্জনক",
    saveData: "ডেটা সংরক্ষণ করুন",
    addAshaWorker: "আশা কর্মী যোগ করুন",
    workerName: "কর্মীর নাম",
    generatePassword: "পাসওয়ার্ড তৈরি করুন",
    sendSMS: "এসএমএস পাঠান",
    viewCharts: "চার্ট দেখুন",
    healthTrends: "স্বাস্থ্যের প্রবণতা",
    waterSourceCondition: "পানির উৎসের অবস্থা",
    clean: "পরিষ্কার",
    muddy: "কাদাযুক্ত",
    stagnant: "স্থির",
    location: "অবস্থান",
    fever: "জ্বর",
    cough: "কাশি",
    diarrhea: "ডায়রিয়া",
    vomiting: "বমি",
    skinIssues: "চামড়ার সমস্যা",
    stomachPain: "পেটে ব্যথা",
    headache: "মাথা ব্যথা",
    bodyPain: "শরীরে ব্যথা"
  },
  tribal: {
    appName: "Smart Health Monitoring",
    tagline: "Community Health & Water Quality",
    selectLanguage: "Select Language",
    english: "English",
    hindi: "हिंदी",
    assamese: "অসমীয়া",
    bengali: "বাংলা",
    tribal: "Tribal Dialects",
    continue: "Continue",
    admin: "Admin",
    ashaWorker: "ASHA Worker",
    selectRole: "Select Your Role",
    login: "Login",
    adminName: "Admin Name",
    villageName: "Village Name",
    workerId: "Worker ID",
    password: "Password",
    dashboard: "Dashboard",
    dataEntry: "Data Entry",
    reports: "Reports",
    alerts: "Alerts",
    settings: "Settings",
    patientInfo: "Patient Information",
    patientName: "Patient Name",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    symptoms: "Symptoms",
    waterQuality: "Water Quality",
    turbidity: "Turbidity",
    pH: "pH Level",
    temperature: "Temperature",
    safe: "Safe",
    warning: "Warning",
    unsafe: "Unsafe",
    saveData: "Save Data",
    addAshaWorker: "Add ASHA Worker",
    workerName: "Worker Name",
    generatePassword: "Generate Password",
    sendSMS: "Send SMS",
    viewCharts: "View Charts",
    healthTrends: "Health Trends",
    waterSourceCondition: "Water Source Condition",
    clean: "Clean",
    muddy: "Muddy",
    stagnant: "Stagnant",
    location: "Location",
    fever: "Fever",
    cough: "Cough",
    diarrhea: "Diarrhea",
    vomiting: "Vomiting",
    skinIssues: "Skin Issues",
    stomachPain: "Stomach Pain",
    headache: "Headache",
    bodyPain: "Body Pain"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('healthMonitorLanguage') as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('healthMonitorLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[Language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};